# Generated by Django 5.1.1 on 2024-09-24 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_feature_product_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updateorder',
            old_name='order_id',
            new_name='order',
        ),
    ]
