# Generated by Django 5.1 on 2024-09-25 06:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_updateorder_status_alter_updateorder_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateorder',
            name='status',
        ),
        migrations.AlterField(
            model_name='updateorder',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
